import time
from time import sleep
print("Wie ist Dein Name?")
name = input()
print("Hallo " + name + " :-)")
print("Wie gehts dir?")
Antwort = input()
if Antwort == "gut":
    print("Freut mich! Mir gehts auch gut!")
if Antwort == "Gut":
    print("Freut mich! Mir gehts auch gut!")
if Antwort == "Gut!":
    print("Freut mich! Mir gehts auch gut!")
if Antwort == "gut!":
    print("Freut mich! Mir gehts auch gut!")
if Antwort == "Sehr gut!":
    print("Super mir gehts auch sehr gut!")
if Antwort == "Sehr gut":
    print("Super mir gehts auch sehr gut!")
if Antwort == "sehr gut!":
    print("Super mir gehts auch sehr gut!")
if Antwort == "sehr gut":
    print("Super mir gehts auch sehr gut!")
if Antwort == "Ganz ok!":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "Ganz ok":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "ganz ok!":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "ganz ok":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "Ok!":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "Ok":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "ok!":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "ok":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Lass uns doch mal zu was anderem kommen :)")
if Antwort == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Lass uns doch mal zu was anderem kommen :)")
if Antwort == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Lass uns doch mal zu was anderem kommen :)")
if Antwort == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Lass uns doch mal zu was anderem kommen :)")
print("Hast du Lust auf Mathe? Bitte nur mit ja oder nein antworten!")
Antwort2 = input()
if Antwort2 == "Ja":
   print("Ok gut dann machen wir jetzt ein bisschen Mathe! xD")
if Antwort2 == "Ja!":
   print("Ok gut dann machen wir jetzt ein bisschen Mathe! xD")
if Antwort2 == "ja!":
   print("Tut mir Leid wir machen jetzt trotzdem Mathe! xD")
if Antwort2 == "Nein!":
   print("Tut mir Leid wir machen jetzt trotzdem Mathe! xD")
if Antwort2 == "nein":
   print("Tut mir Leid wir machen jetzt trotzdem Mathe! xD")
if Antwort2 == "nein!":
   print("Tut mir Leid wir machen jetzt trotzdem Mathe! xD")
if Antwort2 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Fangen wir lieber mit Mathe an :)")
if Antwort2 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Fangen wir lieber mit Mathe an :)") 
if Antwort2 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Fangen wir lieber mit Mathe an :)")
if Antwort2 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Fangen wir lieber mit Mathe an :)")
print("Welche Jahrgangsstufe enspricht deinem Koennen? Antworte bitte nur mit einer Zahl.")
Antwort3 = input()
if Antwort3 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
if Antwort3 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
if Antwort3 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
if Antwort3 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
if Antwort3 == "1":
   print("Ok dann fangen wir an! Bei jeder falschen Antwort wird das Programm automatisch gestoppt und du musst von vorne anfangen also denke genau nach!")
   print("Was ist 2+2?")
   Antwort4 = input()
   if Antwort4 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort4 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
    if Antwort3 == "selbstzerstoerung":
     print("Selbstzerstoerung in 10")
     time.sleep(1)
     print("9")
     time.sleep(1)
     print("8")
     time.sleep(1)
     print("7")
     time.sleep(1)
     print("6")
     time.sleep(1)
     print("5")
     time.sleep(1)
     print("4")
     time.sleep(1)
     print("3")
     time.sleep(1)
     print("2")
     time.sleep(1)
     print("1")
     time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort4 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort4 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort4 == "4":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 6+3?")
   Antwort5 = input()
   if Antwort5 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort5 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort5 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort5 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort5 == "9":
     print("Richtig")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 7-4?")
   Antwort6 = input()
   if Antwort6 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort6 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort6 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit  
   if Antwort6 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit 
   if Antwort6 == "3":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit 
   print("Was ist 10-8?")
   Antwort7 = input()
   if Antwort7 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort7 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit 
   if Antwort7 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit 
   if Antwort7 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort7 == ("2")
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 1+9?")
   Antwort8 = input()
   if Antwort8 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort8 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort8 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort8 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort8 == ("9")
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
     