import time
from time import sleep
print("Wie ist Dein Name?")
name = input()
print("Hallo " + name + " :-)")
print("Wie gehts dir?")
Antwort = input()
if Antwort == "gut":
    print("Freut mich! Mir gehts auch gut!")
if Antwort == "Gut":
    print("Freut mich! Mir gehts auch gut!")
if Antwort == "Gut!":
    print("Freut mich! Mir gehts auch gut!")
if Antwort == "gut!":
    print("Freut mich! Mir gehts auch gut!")
if Antwort == "Sehr gut!":
    print("Super mir gehts auch sehr gut!")
if Antwort == "Sehr gut":
    print("Super mir gehts auch sehr gut!")
if Antwort == "sehr gut!":
    print("Super mir gehts auch sehr gut!")
if Antwort == "sehr gut":
    print("Super mir gehts auch sehr gut!")
if Antwort == "Ganz ok!":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "Ganz ok":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "ganz ok!":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "ganz ok":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "Ok!":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "Ok":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "ok!":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "ok":
    print("Ok klingt aber nicht sehr überzeugend :)")
if Antwort == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Lass uns doch mal zu was anderem kommen :)")
if Antwort == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Lass uns doch mal zu was anderem kommen :)")
if Antwort == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Lass uns doch mal zu was anderem kommen :)")
if Antwort == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Lass uns doch mal zu was anderem kommen :)")
print("Hast du Lust auf Mathe? Bitte nur mit ja oder nein antworten!")
Antwort2 = input()
if Antwort2 == "ja":
   print("Ok gut dann machen wir jetzt ein bisschen Mathe! xD")
if Antwort2 == "Ja!":
   print("Ok gut dann machen wir jetzt ein bisschen Mathe! xD")
if Antwort2 == "ja!":
   print("Tut mir Leid wir machen jetzt trotzdem Mathe! xD")
if Antwort2 == "Nein!":
   print("Tut mir Leid wir machen jetzt trotzdem Mathe! xD")
if Antwort2 == "nein":
   print("Tut mir Leid wir machen jetzt trotzdem Mathe! xD")
if Antwort2 == "nein!":
   print("Tut mir Leid wir machen jetzt trotzdem Mathe! xD")
if Antwort2 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Fangen wir lieber mit Mathe an :)")
if Antwort2 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Fangen wir lieber mit Mathe an :)") 
if Antwort2 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Fangen wir lieber mit Mathe an :)")
if Antwort2 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! Fangen wir lieber mit Mathe an :)")
print("Welche Jahrgangsstufe enspricht deinem Koennen? Antworte bitte nur mit einer Zahl.")
Antwort3 = input()
if Antwort3 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
if Antwort3 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
if Antwort3 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
if Antwort3 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
if Antwort3 == "1":
   print("Ok dann fangen wir an! Bei jeder falschen Antwort wird das Programm automatisch gestoppt und du musst von vorne anfangen also denke genau nach!")
   print("Was ist 2+2?")
   Antwort4 = input()
   if Antwort4 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort4 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
    if Antwort3 == "selbstzerstoerung":
     print("Selbstzerstoerung in 10")
     time.sleep(1)
     print("9")
     time.sleep(1)
     print("8")
     time.sleep(1)
     print("7")
     time.sleep(1)
     print("6")
     time.sleep(1)
     print("5")
     time.sleep(1)
     print("4")
     time.sleep(1)
     print("3")
     time.sleep(1)
     print("2")
     time.sleep(1)
     print("1")
     time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort4 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort4 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort4 == "4":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 6+3?")
   Antwort5 = input()
   if Antwort5 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort5 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort5 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort5 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort5 == "9":
     print("Richtig")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 7-4?")
   Antwort6 = input()
   if Antwort6 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort6 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort6 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit  
   if Antwort6 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit 
   if Antwort6 == "3":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit 
   print("Was ist 10-8?")
   Antwort7 = input()
   if Antwort7 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort7 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit 
   if Antwort7 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit 
   if Antwort7 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort7 == "2":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 1+9?")
   Antwort8 = input()
   if Antwort8 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort8 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort8 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort8 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort8 == "9":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 9-4?")
   Antwort9 = input()
   if Antwort9 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort9 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort9 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort9 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort9 == "5":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 10-9?")
   Antwort10 = input()
   if Antwort10 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort10 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort10 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort10 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort10 == "1":
     print("Richtig!")
   else:
    print("Falsch!")
    SystemExit
   print("Was ist 5+3?")
   Antwort11 = input()
   if Antwort11 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort11 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort11 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort11 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort11 == "8":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 10-4?")
   Antwort12 = input()
   if Antwort12 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort12 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort12 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort12 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort12 == "6":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 8-6?")
   Antwort13 = input()
   if Antwort13 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort13 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort13 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort13 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort13 == "2":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Gut gemacht!")
if Antwort3 == "2":
   print("Ok dann fangen wir an! Bei jeder falschen Antwort wird das Programm automatisch gestoppt und du musst von vorne anfangen also denke genau nach!")
   print("Was ist 34+35?")
   Antwort21 = input()
   if Antwort21 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort21 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort21 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort21 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort21 == "39":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 27+65?")
   Antwort22 = input()
   if Antwort22 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort22 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort22 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort22 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort22 == "92":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 89-64?")
   Antwort23 = input()
   if Antwort23 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort23 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort23 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort23 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort23 == "25":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 19+67?")
   Antwort24 = input()
   if Antwort24 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort24 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort24 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort24 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort24 == "86":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 100-68?")
   Antwort25 = input()
   if Antwort25 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort25 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort25 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort25 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort25 == "32":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 45+31?")
   Antwort26 = input()
   if Antwort26 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort26 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort26 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort26 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort26 == "76":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 85-39?")
   Antwort27 = input()
   if Antwort27 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort27 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort27 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort27 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort27 == "46":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
   print("Was ist 97-83?")
   Antwort28 = input()
   if Antwort28 == "Selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort28 == "selbstzerstoerung!":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort28 == "Selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort28 == "selbstzerstoerung":
    print("Selbstzerstoerung in 10")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("Ok lieber doch nicht! An dieser Stelle musst du leider nochmal von vorne anfangen!")
    SystemExit
   if Antwort28 == "14":
     print("Richtig!")
   else:
     print("Falsch!")
     SystemExit
